### PR TITLE
Added Spray client tracing support

### PR DESCRIPTION
**Pull request by drpacman**
Hi,
Very much appreciate your project, we are exploring using it at the BBC. I have added support for wrapping downstream requests using Spray Client.

Kind Regards
Paul

### CODE REVIEW

**Comment by levkhomich** [comment]
Hi,
I'm glad to see more and more companies using Zipkin. It looks like #28 can be finally closed.
Thank you for contributing to this project!

Regards,
Lev

**Comment by drpacman** [comment]
Hi Lev,
Any chance of creating a release of this code so our projects can reference them as library dependencies from a public repo?

Regards
Paul

**Comment by levkhomich** [comment]
I will take care of that by the end of this week.

**Comment by drpacman** [comment]
Thanks!

**Pull request merged**
