### PR TITLE
issue #88: send trace to server when request context completes

### PR DESCRIPTION
**Pull request by sgluschenko**
Fixing issue #88 
The cause of the issue was `tracedHandleWith` working with code that returned future in this way:
1. It send the trace to server
2. It returned the original value (`Future`), which was then serialized to response.

Sending trace to server to early has following disadvantages:
1. It is not possible to add tracing information based on response.
2. Future evaluation time is not included to request time. In my case it was the biggest part of request processing.

This change sends trace to server in `onComplete` callback of `Future[RouteResult]`, which is obtained from `ctx.complete` method.

### CODE REVIEW

**Comment by levkhomich** [comment]
Could you pleas provide test case for this issue?

**Comment by sgluschenko** [comment]
I've added test to TracingDirectivesSpec, its called "send trace to server only after response future has completed".

**Comment by sgluschenko** [comment]
@levkhomich could you review, please? :)

**Comment by levkhomich** [comment]
It was merged to the latest release (which was a long overdue because of issues with 2.12 support). Thank you for contributing.

**Pull request merged**
